# ====== PROFIL PRODUCTION ======

# Base de données (variables d'environnement Docker)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA — Désactivé en prod (sécurité + performance)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=validate

# JWT (variable d'environnement Docker)
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Upload
app.upload.dir=${APP_UPLOAD_DIR:/app/uploads}

# Swagger — Désactivé en production
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

# Logs
logging.level.root=WARN
logging.level.ma.toubkalit=INFO
